extends: default

rules:
  line-length:
    max: 120
    level: warning
  
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  
  comments:
    min-spaces-from-content: 1
  
  comments-indentation: disable
  
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: true
  
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  
  commas:
    max-spaces-before: 0
    max-spaces-after: 1
  
  hyphens:
    max-spaces-after: 1
  
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1
  
  empty-values:
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true

ignore: |
  .github/
  node_modules/
  venv/
  .venv/