# Production Environment Configuration
# GitHub Environment Protection Rules

name: production
description: Production environment for live service delivery

# Environment Protection Rules
protection_rules:
  # Require 2 reviewers (lead + manager)
  required_reviewers: 2
  
  # 5 minute wait timer for final checks
  wait_timer: 5
  
  # Prevent self-review
  prevent_self_review: true
  
  # Restrict to administrators
  restrict_pushes_to_admins: true
  
  # Reviewers list (configured in GitHub UI)
  # - Development Team Lead
  # - Engineering Manager
  # - DevOps Lead

# Deployment Branch Policy
deployment_branch_policy:
  # Only allow deployment from main branch
  protected_branches: true
  custom_branch_policies: false
  allowed_branches:
    - "main"
    - "hotfix/*"

# Environment Variables
environment_variables:
  NODE_ENV: production
  LOG_LEVEL: warn
  ENVIRONMENT: production
  DEBUG_MODE: "false"
  CACHE_TTL: "3600"
  API_TIMEOUT: "5000"
  
  # Performance optimization
  MAX_CONNECTIONS: "500"
  POOL_SIZE: "50"
  WORKER_PROCESSES: "auto"
  
  # Security settings
  SESSION_TIMEOUT: "900"
  CSRF_PROTECTION: "true"
  RATE_LIMITING: "true"
  
  # Feature flags
  FEATURE_TOGGLE_URL: "https://features.sas-com.example.com"
  
  # CDN Configuration
  CDN_ENABLED: "true"
  STATIC_ASSETS_CDN: "https://cdn.sas-com.example.com"

# Environment Secrets
required_secrets:
  # Database Configuration
  - PROD_DATABASE_URL
  - PROD_DATABASE_PASSWORD
  - PROD_DATABASE_SSL_CERT
  - PROD_DATABASE_ENCRYPTION_KEY
  
  # API Keys
  - PROD_API_KEY
  - PROD_SERVICE_ACCOUNT_KEY
  - PROD_JWT_SECRET
  - PROD_ENCRYPTION_KEY
  
  # External Services
  - PROD_REDIS_URL
  - PROD_REDIS_PASSWORD
  - PROD_ELASTICSEARCH_URL
  - PROD_S3_BUCKET
  - PROD_S3_ACCESS_KEY
  - PROD_S3_SECRET_KEY
  - PROD_CDN_URL
  
  # Payment Integration (production)
  - PROD_PAYMENT_API_KEY
  - PROD_PAYMENT_WEBHOOK_SECRET
  - PROD_PAYMENT_ENCRYPTION_KEY
  
  # Monitoring & Observability
  - PROD_MONITORING_TOKEN
  - PROD_APM_TOKEN
  - PROD_LOGGING_TOKEN
  - PROD_METRICS_TOKEN
  - PROD_TRACING_TOKEN
  
  # Security
  - PROD_SSL_CERT
  - PROD_SSL_PRIVATE_KEY
  - PROD_WAF_TOKEN
  - SECURITY_SCANNER_TOKEN
  
  # External Integrations
  - PROD_CRM_API_KEY
  - PROD_EMAIL_SERVICE_KEY
  - PROD_SMS_SERVICE_KEY
  - PROD_ANALYTICS_TOKEN
  
  # Backup & Recovery
  - PROD_BACKUP_ENCRYPTION_KEY
  - PROD_CROSS_REGION_KEY
  
  # Compliance
  - PROD_AUDIT_TOKEN
  - PROD_COMPLIANCE_KEY

# Deployment Configuration
deployment:
  strategy: blue_green
  timeout_minutes: 60
  
  # Blue-Green Deployment Settings
  blue_green:
    # Traffic switching
    traffic_switching: atomic
    verification_time: 300  # 5 minutes
    
    # Canary settings
    canary_enabled: true
    canary_percentage: 10
    canary_duration: 600  # 10 minutes
  
  # Health Check Configuration
  health_check:
    path: "/health"
    timeout: 120
    retries: 20
    interval: 30
    initial_delay: 60
    
    # Deep health checks
    deep_check_enabled: true
    database_check: true
    external_service_check: true
  
  # Pre-deployment Checks
  pre_deployment:
    - comprehensive_security_scan
    - database_migration_validation
    - integration_test_suite
    - performance_regression_test
    - load_test_validation
    - disaster_recovery_verification
    - compliance_validation
  
  # Post-deployment Validation
  post_deployment:
    - critical_path_validation
    - business_logic_verification
    - performance_baseline_check
    - security_verification
    - backup_validation
    - monitoring_verification
  
  # Resource Configuration
  resources:
    cpu: 2
    memory: 4096Mi
    storage: 100Gi
    
    # Resource requests vs limits
    requests:
      cpu: 1.5
      memory: 3072Mi
    limits:
      cpu: 4
      memory: 8192Mi
  
  # Auto-scaling
  scaling:
    min_replicas: 3
    max_replicas: 10
    target_cpu: 50
    target_memory: 60
    
    # Custom scaling metrics
    custom_metrics:
      - name: requests_per_second
        target: 1000
      - name: database_connections
        target: 80

# High Availability Configuration
high_availability:
  enabled: true
  
  # Multi-zone deployment
  multi_zone: true
  zone_distribution: even
  
  # Anti-affinity rules
  anti_affinity: true
  
  # Circuit breaker
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_timeout: 30
  
  # Graceful shutdown
  graceful_shutdown:
    timeout: 30
    pre_stop_hook: true

# Monitoring Configuration
monitoring:
  enabled: true
  retention_days: 90
  log_level: warn
  
  # Enterprise monitoring
  enterprise_features: true
  distributed_tracing: true
  custom_dashboards: true
  
  # Real-time monitoring
  real_time_alerts: true
  alerting_frequency: immediate
  
  # SLA Monitoring
  sla:
    availability_target: 99.9
    response_time_p95: 200
    response_time_p99: 500
    error_rate_max: 0.1
  
  # Alerts (strict thresholds)
  alerts:
    error_rate_threshold: 0.5
    response_time_threshold: 500
    availability_threshold: 99.5
    
    # Infrastructure alerts
    cpu_usage_threshold: 70
    memory_usage_threshold: 75
    disk_usage_threshold: 75
    database_connection_threshold: 70
    
    # Business metrics
    conversion_rate_threshold: -10  # 10% decrease
    revenue_impact_threshold: -5    # 5% decrease
  
  # Metrics Collection (comprehensive)
  metrics:
    - response_time
    - error_rate
    - throughput
    - cpu_usage
    - memory_usage
    - database_connections
    - cache_hit_ratio
    - queue_length
    - business_metrics
    - security_events
    - compliance_metrics
  
  # Log aggregation
  log_aggregation:
    enabled: true
    structured_logging: true
    log_retention: 365  # 1 year
    log_encryption: true

# Security Configuration (maximum security)
security:
  # Comprehensive security scanning
  vulnerability_scan: true
  license_check: true
  secret_detection: true
  malware_scan: true
  
  # Container Security
  container_scan: true
  base_image_scan: true
  runtime_security: true
  image_signing: true
  
  # Network Security
  network_policies: true
  ingress_whitelist:
    - "203.0.113.0/24"    # Office network only
    - "198.51.100.0/24"   # VPN network
  
  # WAF (Web Application Firewall)
  waf:
    enabled: true
    ddos_protection: true
    rate_limiting: true
    geo_blocking: true
  
  # Security Headers (strict)
  security_headers:
    - "X-Frame-Options: DENY"
    - "X-Content-Type-Options: nosniff"
    - "X-XSS-Protection: 1; mode=block"
    - "Strict-Transport-Security: max-age=63072000; includeSubDomains; preload"
    - "Content-Security-Policy: default-src 'self'"
    - "Referrer-Policy: strict-origin-when-cross-origin"
  
  # Encryption
  encryption:
    data_at_rest: true
    data_in_transit: true
    key_rotation: true
    key_rotation_schedule: "0 0 1 */3 *"  # Quarterly
  
  # Compliance (comprehensive)
  compliance:
    - GDPR
    - PCI_DSS
    - SOX
    - ISO27001
    - HIPAA_applicable_controls
  
  # Security Monitoring
  security_monitoring:
    enabled: true
    threat_detection: true
    anomaly_detection: true
    security_incident_response: automated

# Backup Configuration (enterprise grade)
backup:
  enabled: true
  retention_days: 365  # 1 year
  schedule: "0 1 * * *"  # Daily at 1 AM
  
  # Multiple backup types
  backup_types:
    - database_full
    - database_incremental
    - application_data
    - configuration_files
    - secrets_backup
    - log_files
  
  # Cross-region replication
  cross_region_replication: true
  cross_region_retention: 90
  
  # Backup encryption
  encryption: true
  encryption_key_rotation: true
  
  # Backup verification
  verification:
    enabled: true
    restore_testing: weekly
    integrity_checks: daily

# Database Configuration (production grade)
database:
  # High availability
  high_availability: true
  read_replicas: 2
  failover_timeout: 30
  
  # Migration settings
  migration:
    auto_migrate: false  # Manual approval required
    backup_before_migration: true
    rollback_on_failure: true
    timeout_minutes: 60
    validation_required: true
  
  # Connection pooling
  connection_pool:
    min_connections: 10
    max_connections: 100
    idle_timeout: 300
    connection_lifetime: 3600
  
  # Performance monitoring
  performance_monitoring: true
  slow_query_threshold: 500
  deadlock_detection: true
  
  # Backup strategy
  backup_strategy:
    full_backup: daily
    incremental_backup: hourly
    point_in_time_recovery: true

# Disaster Recovery Configuration
disaster_recovery:
  enabled: true
  
  # RTO/RPO targets
  rto_minutes: 5    # Recovery Time Objective
  rpo_minutes: 15   # Recovery Point Objective
  
  # DR site configuration
  dr_site_enabled: true
  dr_site_sync: real_time
  
  # Failover procedures
  automated_failover: true
  failover_triggers:
    - service_unavailable_5min
    - error_rate_above_10percent
    - response_time_above_10sec
  
  # Testing
  dr_testing:
    schedule: monthly
    full_failover_test: quarterly

# Performance Configuration
performance:
  # CDN configuration
  cdn:
    enabled: true
    cache_ttl: 86400  # 24 hours
    gzip_compression: true
    brotli_compression: true
  
  # Caching strategy
  caching:
    redis_enabled: true
    cache_warming: true
    cache_invalidation: smart
  
  # Database optimization
  database_optimization:
    query_optimization: true
    index_optimization: true
    connection_pooling: optimized

# Notification Configuration (comprehensive)
notifications:
  enabled: true
  channels:
    - teams_production_channel
    - email_leadership_team
    - sms_oncall_team
    - pagerduty_production
  
  # Events to notify (comprehensive)
  events:
    - deployment_start
    - deployment_success
    - deployment_failure
    - health_check_failure
    - performance_degradation
    - security_alert
    - backup_failure
    - compliance_violation
    - sla_breach
    - disaster_recovery_trigger
  
  # Notification preferences (immediate)
  preferences:
    immediate: true
    batched: false
    quiet_hours: false
    
    # Escalation matrix
    escalation:
      level_1:
        after_minutes: 5
        contacts:
          - oncall_engineer
      level_2:
        after_minutes: 15
        contacts:
          - dev_lead
          - devops_lead
      level_3:
        after_minutes: 30
        contacts:
          - engineering_manager
          - cto

# Maintenance Configuration
maintenance:
  # Maintenance windows (minimal)
  windows:
    - day: "sunday"
      start: "03:00"
      end: "04:00"
      timezone: "Asia/Tokyo"
      frequency: "monthly"
  
  # Automatic maintenance (conservative)
  auto_updates: false
  security_patches: true  # Only critical security patches
  dependency_updates: false
  
  # Change management
  change_approval_required: true
  change_window_required: true
  rollback_plan_required: true

# Compliance and Auditing
compliance:
  # Audit logging
  audit_logging: true
  audit_retention_days: 2555  # 7 years
  
  # Compliance frameworks
  frameworks:
    - SOX
    - PCI_DSS
    - GDPR
    - ISO27001
  
  # Regular compliance checks
  automated_compliance_checks: true
  compliance_reporting: monthly
  
  # Data governance
  data_governance:
    data_classification: true
    data_retention_policies: true
    right_to_erasure: true

# Cost Optimization
cost_optimization:
  # Resource optimization
  auto_scaling: true
  spot_instances: false  # Reliability over cost
  
  # Monitoring
  cost_monitoring: true
  budget_alerts: true
  
  # Scheduled scaling
  scheduled_scaling:
    business_hours_scale_up: true
    off_hours_scale_down: false  # 24/7 availability