# Staging Environment Configuration
# GitHub Environment Protection Rules

name: staging
description: Staging environment for integration testing and UAT

# Environment Protection Rules
protection_rules:
  # Require 1 reviewer (dev lead)
  required_reviewers: 1
  
  # No wait timer for staging
  wait_timer: 0
  
  # Prevent self-review
  prevent_self_review: true
  
  # Reviewers list (configured in GitHub UI)
  # - Development Team Lead
  # - Senior Developers

# Deployment Branch Policy  
deployment_branch_policy:
  # Only allow deployment from staging branch
  protected_branches: true
  custom_branch_policies: false
  allowed_branches:
    - "staging"
    - "release/*"
    - "hotfix/*"

# Environment Variables
environment_variables:
  NODE_ENV: production
  LOG_LEVEL: info
  ENVIRONMENT: staging
  DEBUG_MODE: "false"
  CACHE_TTL: "600"
  API_TIMEOUT: "10000"
  
  # Performance tuning
  MAX_CONNECTIONS: "100"
  POOL_SIZE: "10"
  
  # Feature flags
  FEATURE_TOGGLE_URL: "https://staging-features.sas-com.example.com"

# Environment Secrets
required_secrets:
  # Database Configuration
  - STAGING_DATABASE_URL
  - STAGING_DATABASE_PASSWORD
  - STAGING_DATABASE_SSL_CERT
  
  # API Keys
  - STAGING_API_KEY
  - STAGING_SERVICE_ACCOUNT_KEY
  - STAGING_JWT_SECRET
  
  # External Services
  - STAGING_REDIS_URL
  - STAGING_ELASTICSEARCH_URL
  - STAGING_S3_BUCKET
  - STAGING_CDN_URL
  
  # Payment Integration (sandbox)
  - STAGING_PAYMENT_API_KEY
  - STAGING_PAYMENT_WEBHOOK_SECRET
  
  # Monitoring
  - STAGING_MONITORING_TOKEN
  - STAGING_APM_TOKEN
  - STAGING_LOGGING_TOKEN
  
  # Testing
  - STAGING_E2E_TEST_TOKEN
  - STAGING_LOAD_TEST_KEY
  
  # Security Scanning
  - SNYK_TOKEN
  - SEMGREP_APP_TOKEN
  - SECURITY_SCANNER_TOKEN
  
  # External Integrations
  - STAGING_CRM_API_KEY
  - STAGING_EMAIL_SERVICE_KEY
  - STAGING_SMS_SERVICE_KEY

# Deployment Configuration
deployment:
  strategy: rolling_update
  timeout_minutes: 30
  
  # Rolling Update Settings
  rolling_update:
    max_unavailable: 1
    max_surge: 1
  
  # Health Check Configuration
  health_check:
    path: "/health"
    timeout: 60
    retries: 10
    interval: 15
    initial_delay: 30
  
  # Pre-deployment Checks
  pre_deployment:
    - database_migration_check
    - dependency_vulnerability_scan
    - integration_test_suite
  
  # Post-deployment Validation
  post_deployment:
    - smoke_tests
    - integration_tests
    - performance_baseline_check
  
  # Resource Limits
  resources:
    cpu: 1
    memory: 2048Mi
    storage: 50Gi
  
  # Auto-scaling
  scaling:
    min_replicas: 2
    max_replicas: 5
    target_cpu: 60
    target_memory: 70

# Monitoring Configuration
monitoring:
  enabled: true
  retention_days: 30
  log_level: info
  
  # Enhanced monitoring
  enhanced_metrics: true
  distributed_tracing: true
  
  # Alerts
  alerts:
    error_rate_threshold: 2.0
    response_time_threshold: 1000
    availability_threshold: 95.0
    
    # Custom alerts
    database_connection_threshold: 80
    memory_usage_threshold: 85
    disk_usage_threshold: 80
  
  # Metrics Collection
  metrics:
    - response_time
    - error_rate
    - throughput
    - cpu_usage
    - memory_usage
    - database_connections
    - cache_hit_ratio
    - queue_length
  
  # SLA Monitoring
  sla:
    availability_target: 95.0
    response_time_p95: 500
    error_rate_max: 1.0

# Security Configuration
security:
  # Comprehensive security scanning
  vulnerability_scan: true
  license_check: true
  secret_detection: true
  
  # Container Security
  container_scan: true
  base_image_scan: true
  runtime_security: true
  
  # Network Security
  network_policies: true
  ingress_whitelist:
    - "10.0.0.0/8"      # Internal network
    - "192.168.0.0/16"  # VPN network
    - "203.0.113.0/24"  # Office network
  
  # Security Headers
  security_headers:
    - "X-Frame-Options: DENY"
    - "X-Content-Type-Options: nosniff"
    - "X-XSS-Protection: 1; mode=block"
    - "Strict-Transport-Security: max-age=31536000"
  
  # Compliance
  compliance:
    - GDPR
    - PCI_DSS_validation
    - SOX_controls

# Backup Configuration
backup:
  enabled: true
  retention_days: 30
  schedule: "0 2 * * *"  # Daily at 2 AM
  
  # Backup Types
  backup_types:
    - database_full
    - database_incremental
    - application_data
    - configuration_files
  
  # Cross-region backup
  cross_region_replication: true

# Database Configuration
database:
  # Migration settings
  migration:
    auto_migrate: true
    backup_before_migration: true
    rollback_on_failure: true
    timeout_minutes: 20
  
  # Connection pooling
  connection_pool:
    min_connections: 5
    max_connections: 20
    idle_timeout: 300
  
  # Performance monitoring
  performance_monitoring: true
  slow_query_threshold: 1000

# Load Testing Configuration
load_testing:
  enabled: true
  schedule: "0 1 * * 1"  # Weekly on Monday at 1 AM
  
  # Test scenarios
  scenarios:
    - baseline_load
    - stress_test
    - spike_test
  
  # Thresholds
  thresholds:
    max_response_time: 2000
    max_error_rate: 1.0
    min_throughput: 100

# Notification Configuration
notifications:
  enabled: true
  channels:
    - teams_staging_channel
    - email_dev_team
  
  # Events to notify
  events:
    - deployment_start
    - deployment_success
    - deployment_failure
    - health_check_failure
    - performance_degradation
    - security_alert
  
  # Notification preferences
  preferences:
    immediate: true
    batched: false
    quiet_hours: false
    
    # Escalation
    escalation:
      after_minutes: 15
      contacts:
        - dev_lead_email
        - manager_email

# Maintenance Configuration
maintenance:
  # Maintenance windows
  windows:
    - day: "sunday"
      start: "02:00"
      end: "04:00"
      timezone: "Asia/Tokyo"
  
  # Automatic maintenance
  auto_updates: true
  security_patches: true
  dependency_updates: false